### ISSUE TITLE
Feature Request: Please Register it with WordPress Packagist

### ISSUE THREAD

**Issue by DaviTeodoro** [bordoni/fakerpress#101]
Hi Gustavo, 
Would be great if we could use it as a composer pack. As a plugin that is use most on development I think it would make total sense. To do so it need to be register it with https://wpackagist.org/. 
Thank you

**Comment by njbarrett** [comment]
I installed it with wpackagist just fine.

I just added `"wpackagist-plugin/fakerpress": "*",` and composer update.

**Comment by DaviTeodoro** [comment]
Thank you
