### ISSUE TITLE
Unable to fill metabox fields

### ISSUE THREAD

**Issue by stratboy** [bordoni/fakerpress#105]
Hi! Thank you for your plugin.

I've got a problem: cannot fill in fileds inside custom metaboxes.

I've got a metabox, say _sottotioli_film, that has 2 text fields inside. Cannot have theme filled up.
On the Meta Field Rules I'm sayng it's words, 2, 90 weight, and as name I put _sottotioli_film. Doesn't work. Why? How to?

Thank you, regards.

**Comment by bordoni** [comment]
Hey @stratboy, actually found a few bugs around the Taxonomies and Meta fields, so I'm planning on a release in December to fix this up. Sorry for the big delay there.

**Comment by lbngoc** [comment]
Same problem here when create fake data for terms with term metadata :(
