### ISSUE TITLE
Feature Request: Network Option for 500px api key

### ISSUE THREAD

**Issue by 0aveRyan** [bordoni/fakerpress#107]
It'd be great if the 500px API key persisted between sites as a network option in WordPress Multisite!

**Comment by bordoni** [comment]
Ohh nice, I like that Idea, will see an Option to do that.

**Comment by bordoni** [comment]
Moved it out of the `0.4.10` to allow me to release a good bug fix, might either come on `0.4.11` or in a `0.5.X` version, later on this year.

**Comment by bordoni** [comment]
No longer required since 500px deprecated their APis.
