### ISSUE TITLE
Cache taxonomy terms

### ISSUE THREAD

**Issue by fbm-static** [bordoni/fakerpress#108]
When selecting terms under Taxonomy Field Rules, the terms are always AJAX-queried everytime you click on the terms field. Would also be nice to easily add all of the terms available.

**Comment by bordoni** [comment]
Currently, if you leave all it Empty it will use any terms from that Taxonomy. Unfortunately, we cannot implement cache with the Current version of Select2, which might change in the future. But for now, we are stuck with this lack of caching.
