### ISSUE TITLE
Create a l18n bin File to grab Files from Transifex

### ISSUE THREAD

**Issue by bordoni** [bordoni/fakerpress#12]
Right now we don't have translations as we wanted, so the procedure should be go to Transifex grab all the `.po` files download them and create the `.mo` files before the `svn-push`

**Comment by fxbenard** [comment]
Check out how we're using tx client and grunt for doing it https://github.com/WP-Translations/grunt-transifex-wordpress

**Comment by bordoni** [comment]
@fxbenard Im thinking about moving to WP.org GlotPress, not sure yet.
