### ISSUE TITLE
The info should be updated to indicate https://translate.wordpress.org/  for translations

### ISSUE THREAD

**Issue by ujdhesa** [bordoni/fakerpress#123]
Hello, 

https://translate.wordpress.org/ is the place where to contribute translations of the plugin. The info here still points users to Transifex. Please change the link accordingly.

**Comment by bordoni** [comment]
Ohh Thanks dude, didn't see that we still had people been pointed to Transifex.

**Comment by bordoni** [comment]
Resolved by 92ce96f
