### ISSUE TITLE
Can't select quantity using selector - FakerPress

### ISSUE THREAD

**Issue by rahmantanvir** [bordoni/fakerpress#124]
#### Expected behavior
Quantity should be changeable using selector. 

#### Actual behavior
Quantity is vanishing or not properly changing in the plugin.

#### How to reproduce
1) Install WordPress.
2) Install FakerPress plugin and activate it.
3) Give a random amount of quantity.
4) Try to change min quantity using selector.

* Browser: Chrome
* Operating system: Windows 10

#### Recording Of The Bug
![bug1.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517374854/oywcqwegwwehnmdp4a6n.gif)

**Comment by bordoni** [comment]
Ohhh nice catch, I will take a look at it.
