### ISSUE TITLE
Free API access for 500px is being discontinued on 2018-June-15

### ISSUE THREAD

**Issue by jshipc** [bordoni/fakerpress#128]
From their website:
API
The history of 500px has always encouraged creative development, but as of January 24th 2018, 500px will no longer be offering free access to our API. This decision was made in order to protect our assets and improve our website's performance. On June 15th, access to the API will be shut down. This is part of a larger strategic shift—focusing our energy on continuing to build the world’s best photography community at 500px.com.

I have an existing key, so what does this mean for me? 

If you have an existing API key, you will lose access on June 15th 2018. You can email sales@500px.com to discuss further usage of the API. 

Source: https://support.500px.com/hc/en-us/articles/360002435653-API-

**Comment by bordoni** [comment]
Yea @jshipc,

I saw that, that is very unfortunate, I am working on removing 500px from the places we use to fetch images, and looking at good replacements.

I am to release something before May 20th.

**Comment by bordoni** [comment]
Resolved on version `0.5.0` thanks for the report @jshipc, took way too long for me to get to it but I am back into maintaining FakerPress.
