### ISSUE TITLE
Silently fails when it fails creating post thumbnail

### ISSUE THREAD

**Issue by jmcbee** [bordoni/fakerpress#129]
Apparently, `wp-content/uploads` was not writable by the webserver but the plugin still kept on generating posts with the failed media insert. When I navigate to Media, I see a bunch of non-existent thumbnails. When I click on one, The URL points to a directory (e.g. `http://wp.df/wp-content/uploads/2018/06`).

I think [this line should check for $upload['error']](https://github.com/bordoni/fakerpress/blob/98cbad7e3f2cf8e41b9968203ee8ab6282663f48/modules/attachment.php#L45).

**Comment by bordoni** [comment]
Resolved with the latest version of FakerPress `0.5.0`
