### ISSUE TITLE
Faking Posts doesn't work!

### ISSUE THREAD

**Issue by usrnm-nk** [bordoni/fakerpress#130]
No matter how many posts i put in the "Quantity" field, I always get between 1 to 4 posts and only one of them has featured image.

No success or fail messages are shown!
![fp](https://user-images.githubusercontent.com/40398108/42853366-dd586860-8a2d-11e8-8cd8-356c3a1217b6.png)

WP v4.9.7, FP v0.4.11

**Comment by usrnm-nk** [comment]
Hello?

**Comment by bordoni** [comment]
Closing as my super delayed answer probably will not be helpful here.

Just for safety that seems to be a Fatal, tuning your `WP_DEBUG` will show the message there.
