### ISSUE TITLE
Bug : Error when generate post with number meta field

### ISSUE THREAD

**Issue by PhakphumV** [bordoni/fakerpress#168]
## Issue description
I got an error when trying to generate posts with a number meta field as the following message:

```
Fatal error: Uncaught Error: Unknown named parameter $min
in ./wp-content/plugins/fakerpress/src/FakerPress/Provider/WP_Meta.php on line 56
```

## Reproduction steps
1. Login to Admin panel
2. Go to FakerPress -> Posts menu 
3. Fill in the inputs for generate posts
4. Add meta field with type as Number and fill in min, max possible numbers
5. Click Generate button

**Comment by bordoni** [comment]
Thank you! I will address that on my next PR.

**Comment by PhakphumV** [comment]
Thank you for closing this issue. Really appreciate your work!
