### ISSUE TITLE
Placeholder.com is defunct

### ISSUE THREAD

**Issue by cgarofalo** [bordoni/fakerpress#170]
Placeholder.com is no longer a placeholder image service. It should be replaced with [placehold.co](https://placehold.co) instead.

**Comment by bordoni** [comment]
I am planning a release soon I will make sure to include this. Thank you so much for the report.

**Comment by sclark3-godaddy** [comment]
This was an easy fix on my end locally, switching from vip.placeholder.com to placehold.co in most places.

**Comment by bordoni** [comment]
Related to: https://wordpress.org/support/topic/no-images-67/
