### ISSUE TITLE
Change source ipsum

### ISSUE THREAD

**Issue by valeriosouza** [bordoni/fakerpress#24]
I wish I could choose between, lorem ipsun, bacon ipson, cumpade ipsum, mussum ipsum

**Comment by luancuba** [comment]
@bordoni , what you want to do ? create a new class for the other ipsums at Faker or FakerPress source?

**Comment by bordoni** [comment]
Check out the files on `/providers/text/bacon.php`, you will only need to change the words to follow the base of from: http://baconipsum.com/json-api/

**Comment by bordoni** [comment]
Decided not to implement this feature for now.
We templates are implemented we might allow more dictionaries for the types of data created.
