### ISSUE TITLE
Use batches of AJAX requests when generating data

### ISSUE THREAD

**Issue by fjarrett** [bordoni/fakerpress#53]
I think the data should be generated in a batch of AJAX requests with something like ~100 fake items for each request. This will avoid getting max execution time fatal errors for very large generations.

```
Fatal error: Maximum execution time of 30 seconds exceeded in /srv/www/wordpress-trunk/wp-includes/formatting.php on line 1764
```

This method would also then allow for a nifty progress bar in the UI so you could see how the data generation process is coming along :smiley: 

/cc @bordoni

**Comment by bordoni** [comment]
Version _0.4.0_ is going to be all about that! I've been wanting to do it for a while, but I wanted to get the Meta out first.

**Comment by fjarrett** [comment]
@bordoni Awesome! /five!

**Comment by vpratfr** [comment]
+1 on that. Just have the same problem for 5000 fake users (to test my plugin queries)
