### ISSUE TITLE
Lorempixel as a provider?

### ISSUE THREAD

**Issue by examinedliving** [bordoni/fakerpress#58]
In grepping through your source code, I found lots of tests with http://lorempixel.com as an image provider, but nothing in the core modules.  I briefly tried to hack this myself, and thought I had it, and it worked, but... it didn't work - the images still came from placeholdit.

Do you have any plans of implementing Lorempixel as a provider?  Is there a simple template to create it?  

I copied placeholdit.php to lorempixel.php in the same directory, and modified it as needed, and looked for every possible reference to update across the files, but I must've missed some or done something else wrong.

At any rate, I still have the hacked version in storage, and if there is some sort of way to easily tell me where I need to alter code, I could probably get it working and submit a pull request.  Or maybe there is some other way to go about this?  

Super useful plugin by the way.  It has saved me an incalculable amount of time.

**Comment by bordoni** [comment]
Hey @examinedliving, I wasn't planning on including this one but seems like a good idea. I will do it for our next version. 

It should be released soon, I'm still thinking on how to present this on the UI.

**Comment by examinedliving** [comment]
> It should be released soon, I'm still thinking on how to present this on the UI.

You mean on the post itself, or on the backend?  Seems pretty straightforward..but maybe I'm missing something.

Whatever it is; good to know that you are on it.  I will leave this open for your reply if you have an answer, or, if you don't, feel free to close.  Thanks for getting back to me quickly.

**Comment by bordoni** [comment]
Nahh I will leave it open, so that we have a track of what happened. The thing is that I want to give the users the option of choosing a category or the sizes of the images, something like that.
