### ISSUE TITLE
Lorempixel not working

### ISSUE THREAD

**Issue by examinedliving** [bordoni/fakerpress#61]
Although lorempixel is available as a provider (thanks!), all images generated are still from placehold.it.  Probably forgot to carry the one? ;)

**Comment by bordoni** [comment]
Featured image or html images?

**Comment by examinedliving** [comment]
Inline images (in the post) - is that what you mean?

**Comment by bordoni** [comment]
Yes, that is what I mean.

**Comment by bordoni** [comment]
So I've wrote a new Patch to fix this issue. It will be released with 0.3.3 next Monday.
