### ISSUE TITLE
Too many Items been generated

### ISSUE THREAD

**Issue by luancuba** [bordoni/fakerpress#63]
I tried to create some users and chose a randomized quantity from 1 to 10. I clicked several times on the "Generate" button and were created over a hundred items.
The same goes for posts, comments and terms.

**Comment by bordoni** [comment]
I've tried to reproduce this bug and I wasn't able to, can you provide me a list of which plugins were active at the time?

**Comment by luancuba** [comment]
None plugin is activated unless FakerPress.

**Comment by luancuba** [comment]
I can record a video explaining exactly the bug

**Comment by bordoni** [comment]
Please do :+1:

**Comment by luancuba** [comment]
https://cloudup.com/cBB4XF7YMos

**Comment by bordoni** [comment]
This problem was fixed with #68
