### ISSUE TITLE
Error with array_shift in DateBetween

### ISSUE THREAD

**Issue by ethanclevenger91** [bordoni/fakerpress#64]
When adding custom date meta, there seems to be a bug. If you use a custom range of dates, the `$interval` variable in the function `meta_type_date` in `wp-meta.php` looks like this:

`array('name'=>'', 'min'=>'valid date', 'max'=>'valid date');`

However, the function goes on to use `array_shift` to get the `$min` and `$max` values. So `name` ends up in `$min` and `min` ends up in `$max`. When not using a pre-defined range, this results in an error (`Start date must be anterior to end date`) and if you did define a range, it'll try to format the string name of the range as a date, which won't error, but also won't output what you asked for.

Creating pull request now. I know you mentioned that you wanted to do something other than an indexed array, and I'd be interested to know what that is, as grabbing values by key seems pretty future-proof.

**Comment by bordoni** [comment]
If you fix it in a Pull Request, I will love it!

I might change it a bit for the release but I will love to see contributions that make the plugin work better. :grin:

**Comment by ethanclevenger91** [comment]
Yup. One more question - contributing.md says to issue PRs to the develop branch, but I don't see that branch.

**Comment by bordoni** [comment]
Thanks for the not about the `contributing.md` I forgot that I changed that; :smile:

**Comment by bordoni** [comment]
Thanks for the PR @ethanclevenger91!

**Comment by ethanclevenger91** [comment]
NP - thanks for the work on this excellent plugin
