### ISSUE TITLE
Support for Custom Meta Box 2 

### ISSUE THREAD

**Issue by sharedmit** [bordoni/fakerpress#76]
Support for CMB2 (https://github.com/WebDevStudios/CMB2) would be great.

**Comment by bordoni** [comment]
Hi @sharedmit what do you mean? I do not follow what type of module I should try to create to support CMB2.

**Comment by sharedmit** [comment]
I used CMB2 to add meta fields to my custom posts. How would I go about generating the fake data for those fields?
![add new product zoorya wordpress](https://cloud.githubusercontent.com/assets/1515815/11168393/5dba3b5a-8b9e-11e5-89ed-73a0cd4d4777.png)

**Comment by bordoni** [comment]
You will need to find out what are the **Meta** the CMB2 is using for these 3 fields. Then use the Meta fields configuration to generate the data for it.

![screen shot 2015-11-15 at 22 44 23](https://cloud.githubusercontent.com/assets/236579/11172218/75186db6-8bea-11e5-961a-e6f094fda6e0.png)

**Comment by sharedmit** [comment]
Okay sorry I think I need to clarify what am trying to accomplish. For example the meta field `brand` for my custom post `product` is a drop down list of my custom post `brand`. I guess what am trying to achieve is use custom posts as meta field values.

**Comment by bordoni** [comment]
Ohh ok, so you need to use a `WP_Query` meta to "Randomly" select one.

Use this the Query String field:
`posts_per_page=-1&post_type=brand`

IF you need to be specific you can refer to the [WP_Query](https://codex.wordpress.org/Class_Reference/WP_Query) page on the Codex.

**Comment by sharedmit** [comment]
Awesome! BTW great job on FakerPress. Really <3 it .

**Comment by bordoni** [comment]
Thanks a lot @sharedmit, if you haven't already, please [leave a Review on the WordPress.org repository](http://wordpress.org/support/view/plugin-reviews/fakerpress#postform), it really helps me!
