### ISSUE TITLE
Adding posts: Add Post Title to parent page selection field

### ISSUE THREAD

**Issue by ginsterbusch** [bordoni/fakerpress#77]
hi there,

When adding pages, and wanting to select a parent page, the ID as title in the selection field is rather useless. You'd have to look em up if you wanted to select the correct page (and enable them before, too).

Adding just the post title, maybe in brackets, like so:

```
Page-ID 123 (What a lovely day)
Page-ID 345 (To die)
```

Would help a lot!

cu, w0lf.

**Comment by bordoni** [comment]
Yeah you are completely right on that one, I don't know on which point I decided to use IDs... but it was not a good decision, and since I don't use the parent option that much, I just forgot to change it back. It will be on the next point release.

**Comment by bordoni** [comment]
Hi @ginsterbusch took me forever to complete this, but now it's done. It will come out next week.
