### ISSUE TITLE
Failure to activate

### ISSUE THREAD

**Issue by MurdochM** [bordoni/fakerpress#78]
Hi: I'm using WordPress in a local installation through Instant WordPress and I've several times attempted to install/activate FakerPress both by using the WP directory/install route and by download and seeking to install the zip file.

In each case Install appears to work correctly but I can never activate the plug-in, invariably getting the following error message: Fatal error: Call to a member function parse() on a non-object in J:\InstantWP_4.5\iwpserver\htdocs\wordpress\wp-content\plugins\fakerpress\inc\vendor\Faker\src\Faker\Provider\Address.php on line 95

This then ties up proper access to the WP dashboard or anywhere else until the Fakerpress directory cited is deleted from the drive. All other plug-ins, both large and small, install and activate without difficulty. As I imply above the error is consistently repeatable.

Regards, MM

**Comment by MurdochM** [comment]
Sorry - I should have added that I'm using Wordpress 4.4 and that the active template is Headway 3.8.5. MM

**Comment by bordoni** [comment]
Thanks @MurdochM, I will check on to that. Sorry for the huge delay on answering.

**Comment by bordoni** [comment]
Tried my best to reproduce and couldn't if it ever comes back as I bug I will mark as duplicate.
