### ISSUE TITLE
Feature Request: Add option to determine image sizes

### ISSUE THREAD

**Issue by COLABORATI** [bordoni/fakerpress#86]
It would be great to have the ability in Fakerpress to determine the image sizes of created / imported images.

**Comment by bordoni** [comment]
Hi @COLABORATI, thats actually a very good addition to the codebase I will work on that for the next version.

**Comment by dmccan** [comment]
I'm getting into FakerPress. Thanks!

Yes, it would be nice to be able to set the featured image size that gets created.

**Comment by micalexander** [comment]
How is this coming along? Really need this.
