### ISSUE TITLE
Taxonomy Field Rule Quantity Input Box not clearly understandable

### ISSUE THREAD

**Issue by COLABORATI** [bordoni/fakerpress#90]
In the Taxonomy Field Rule settings form there is a Quantity Input Box - it is not clearly understandable what exactly is expected to input there. There is a help text that reads _"How many terms will be selected"_ but I can not parse the meaning of the two input boxes: 

```
NUMBER INPUT 1 > NUMBER INPUT 2
```

What exactly is the meaning of that input box placement with that "greater than" between them? When I put a number of 1 in the first input box I hope that fakerpress will select one word from the configured taxonomy, but what I see is `1 > 4` - and that does not make any sense - 1 is not greater than 4. 
What is the meaning of these two boxes? Thanks for your attention!

**Comment by bordoni** [comment]
The meaning is: From _"Input 1"_ to _"Input 2"_, so it will randomize a number from `1` to `4` in your case. I hope I resolved your question, but I agree that is not understandable it's something hard to put in words... If you have suggestions I will gladly put then on the plugin 😉
