### ISSUE TITLE
Configure Word List

### ISSUE THREAD

**Issue by jaswsinc** [bordoni/fakerpress#92]
Let me start by saying THANK YOU for creating this plugin. Huge time-saver.

Here's an idea for a new feature:

- Let the word list be configured from the Dashboard or through a filter. I'm using your plugin to create fake content for demonstration purposes and the Lorem Ipsum just looks like a foreign language in my videos. I was able to configure the word list by editing the PHP class file, but if that was configurable in the Dashboard I'm betting a lot of folks would appreciate it.

## Thanks again. You rock! :-)

**Comment by jaswsinc** [comment]
Oops. NM :-) I see you can already do this. Very cool. Thanks.

**Comment by bordoni** [comment]
Nice that you were able to accomplish it man. There is still plenty to do in terms of filters but glad you found what you needed.
