### ISSUE TITLE
Sensible defaults

### ISSUE THREAD

**Issue by rayrutjes** [bordoni/fakerpress#93]
Hi there, to begin with your plugin is great, and really of great use for development.

May I suggest you put some sensible defaults on fields like `Quantity` could reasonably be set to 5 by default, speeding up our testing process!

**Comment by bordoni** [comment]
So instead of defaults, I will add a browser stored last value.  Which should allow for a faster usage.

**Comment by bordoni** [comment]
Decided to not implement this since we are going to have a way to generate a template for which settings you want.
