### ISSUE TITLE
Tags & Categories not being assigned

### ISSUE THREAD

**Issue by rayrutjes** [bordoni/fakerpress#94]
It is not clear what the behaviour is for attaching categories and tags to posts.

Either way, whatever i fill the concerned inputs with, categories and tags are never added to the posts.

Using WP 4.5 and PHP 5.6

Weirdly on WP 3.5.2 with PHP 5.3 categories are being attached, but there are other issues but you don't claim to support that version so I won't bother you with those.

Question: By default if the `terms to assign` is empty, will it choose randomly between the available one or skip totally terms assignment? The former would be great!

Keep it up!!!

**Comment by bordoni** [comment]
Fixed this problem on #95
