### ISSUE TITLE
Please consider joining forces with trendwerk/faker

### ISSUE THREAD

**Issue by COLABORATI** [bordoni/fakerpress#98]
Hey, please take a look at [faker](https://github.com/trendwerk/faker) - they are reinventing a wp-cli version of fakerpress and I believe it would be great for everybody if you would like to [join forces](https://github.com/trendwerk/faker/issues/4). Thanks!

**Comment by bordoni** [comment]
@COLABORATI definitely a wp-cli command for FakerPress is something that I want to create.
But there are a few things that I need to improve on the current codebase to make this work. I would gladly work with the Other developers to make it happen.

**Comment by bordoni** [comment]
I am going to implement the CLI feature on version `0.5.0` so I am closing this in favor of #88
